version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - npm install -g nodemon
      - npm install --legacy-peer-deps
  build:
    commands:
      - npm run build

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'build/**/*'
    - tsconfig.json
    - 'templates/**/*'
    - 'private/**/*'
    - 'images/**/*'
    - 'environment/**/*'
    - 'public/**/*'
  discard-paths: no