name: Catalogue-API

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up SSH for Production
      if: github.ref == 'refs/heads/main'
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.Catalogue_PROD_SSH_KEY }}

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --prefer-offline --no-audit --progress=false
    
    - name: Build Node app
      run: npm run build

    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ github.ref == 'refs/heads/main' && secrets.Catalogue_PROD_KNOWN_HOSTS || github.ref == 'refs/heads/staging' && secrets.Catalogue_PROD_KNOWN_HOSTS || github.ref == 'refs/heads/develop' && secrets.Catalogue_PROD_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
    
    - name: Create .env Production
      if: github.ref == 'refs/heads/main'
      env:
        ENV_FILE: ${{ secrets.Catalogue_PROD_ENV_FILE }}
      run: |
        ssh ubuntu@${{ secrets.Catalogue_PROD_HOST }} "
          echo '${ENV_FILE}' | sudo tee /home/ubuntu/tcctechapinew/.env > /dev/null"
    
    - name: Deploy using rsync on Production
      if: github.ref == 'refs/heads/main'
      env:
        EC2_HOST: ${{ secrets.Catalogue_PROD_HOST }}
      run: |
        rsync -chrlvzi --checksum --delete \
          -e 'ssh -o StrictHostKeyChecking=yes -p 22' \
          --exclude '.git' \
          --exclude '.env' \
          ./ ubuntu@${EC2_HOST}:/home/ubuntu/tcctechapinew/

    - name: Run migration on server
      run: |
        ssh ubuntu@${{ secrets.Catalogue_PROD_HOST }} '
        export NVM_DIR="$HOME/.nvm";
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh";
        cd /home/ubuntu/tcctechapinew && npm run migrate;
        '


    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      env:
        EC2_HOST: ${{ secrets.Catalogue_PROD_HOST }}
      run: |
        ssh -t ubuntu@${EC2_HOST} << 'EOF'
        export NVM_DIR="$HOME/.nvm"
        source $NVM_DIR/nvm.sh
        source $NVM_DIR/bash_completion
        nvm use default
        export PATH="$NVM_DIR/versions/node/v20.18.0/bin:$PATH"
        cd /home/ubuntu/tcctechapinew/
        pm2 restart "CatalogueAPI"
        EOF
