# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ROYALE

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install

    - name: Set up environment file
      run: |
        touch .env
        echo "${{ github.ref == 'refs/heads/main' && secrets.PROD_ENV_VARIABLES || secrets.TCCSTAG_ENV_VARIABLES }}" > .env

    - name: Build Node app
      run: npm run build

    - name: Deploy to EC2 using rsync
      run: |
        echo "${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_SSH_KEY || secrets.ROYALESSH_PRIVATE_KEY }}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chrlvzi --delete \
          -e 'ssh -i ./deploy_key -p 22 -o StrictHostKeyChecking=no' \
          --exclude '/deploy_key' \
          --exclude '.git' \
          --exclude '.env' \
          ./ ubuntu@${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_HOST || secrets.ROYALESTAG_EC2_HOST }}:/home/ubuntu/tcctechapinew/

    - name: PM2 restart
      run: |
          echo "${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_SSH_KEY || secrets.ROYALESSH_PRIVATE_KEY }}" > deploy_key
          chmod 600 ./deploy_key
          ssh -i ./deploy_key ubuntu@${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_HOST || secrets.ROYALESTAG_EC2_HOST }} -p 22 '
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v22.0.0/bin;
            pm2 restart 0
          '
