name: TCC-API

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up SSH for Development
      if: github.ref == 'refs/heads/develop'
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.TCC_DEV_SSH_KEY }}

    - name: Set up SSH for Staging
      if: github.ref == 'refs/heads/staging'
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.TCC_STAG_SSH_KEY }}

    - name: Set up SSH for Production
      if: github.ref == 'refs/heads/main'
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.TCC_PROD_SSH_KEY }}

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --prefer-offline --no-audit --progress=false
    
    - name: Build Node app
      run: npm run build

    - name: Add EC2 to known hosts
      run: echo "${{ github.ref == 'refs/heads/main' && secrets.TCC_PROD_KNOWN_HOSTS || github.ref == 'refs/heads/staging' && secrets.TCC_STAG_KNOWN_HOSTS || github.ref == 'refs/heads/develop' && secrets.TCC_DEV_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
    
    - name: Create .env Development
      if: github.ref == 'refs/heads/develop'
      env:
        ENV_FILE: ${{ secrets.TCC_DEV_ENV_FILE }}
      run: |
        ssh root@${{ secrets.TCC_DEV_HOST }} "
          echo '${ENV_FILE}' | sudo tee /var/www/tcctech-dev/tcctechapinew/.env > /dev/null"

    - name: Create .env Staging
      if: github.ref == 'refs/heads/staging'
      env:
        ENV_FILE: ${{ secrets.TCC_STAG_ENV_FILE }}
      run: |
        ssh root@${{ secrets.TCC_STAG_HOST }} "
          echo '${ENV_FILE}' | sudo tee /var/www/tcctech-stag/tcctechapinew/.env > /dev/null"

    - name: Create .env Production
      if: github.ref == 'refs/heads/main'
      env:
        ENV_FILE: ${{ secrets.TCC_PROD_ENV_FILE }}
      run: |
        ssh ubuntu@${{ secrets.TCC_PROD_HOST }} "
          echo '${ENV_FILE}' | sudo tee /home/ubuntu/tcctechapinew/.env > /dev/null"
        
    - name: Deploy using rsync on development
      if: github.ref == 'refs/heads/develop'
      env:
        EC2_HOST: ${{ secrets.TCC_DEV_HOST }}
      run: |
        rsync -chrlvzi --checksum --delete \
          -e 'ssh -o StrictHostKeyChecking=yes -p 22' \
          --exclude '.git' \
          --exclude '.env' \
          ./ root@${EC2_HOST}:/var/www/tcctech-dev/tcctechapinew/
    
    - name: Deploy using rsync on staging
      if: github.ref == 'refs/heads/staging'
      env:
        EC2_HOST: ${{ secrets.TCC_STAG_HOST }}
      run: |
        rsync -chrlvzi --checksum --delete \
          -e 'ssh -o StrictHostKeyChecking=yes -p 22' \
          --exclude '.git' \
          --exclude '.env' \
          ./ root@${EC2_HOST}:/var/www/tcctech-stag/tcctechapinew/
    
    - name: Deploy using rsync on production
      if: github.ref == 'refs/heads/main'
      env:
        EC2_HOST: ${{ secrets.TCC_PROD_HOST }}
      run: |
        rsync -chrlvzi --checksum --delete \
          -e 'ssh -o StrictHostKeyChecking=yes -p 22' \
          --exclude '.git' \
          --exclude '.env' \
          ./ ubuntu@${EC2_HOST}:/home/ubuntu/tcctechapinew/

    # - name: Run migration on Development
    #   if: github.ref == 'refs/heads/develop'
    #   run: |
    #     ssh root@${{ secrets.TCC_DEV_HOST }} '
    #     export NVM_DIR="$HOME/.nvm";
    #     [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh";
    #     cd /var/www/tcctech-dev/tcctechapinew && npm run migrate;
    #     '   
        
    - name: Run migration on Staging
      if: github.ref == 'refs/heads/staging'
      run: |
        ssh root@${{ secrets.TCC_STAG_HOST }} '
        export NVM_DIR="$HOME/.nvm";
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh";
        cd /var/www/tcctech-stag/tcctechapinew && npm run migrate;
        '   
    
    - name: Run migration on Production
      if: github.ref == 'refs/heads/main'
      run: |
        ssh ubuntu@${{ secrets.TCC_PROD_HOST }} '
        export NVM_DIR="$HOME/.nvm";
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh";
        cd /home/ubuntu/tcctechapinew && npm run migrate;
        ' 

    - name: Deploy to Devlopment
      if: github.ref == 'refs/heads/develop'
      env:
        EC2_HOST: ${{ secrets.TCC_DEV_HOST }}
      run: |
        ssh -t root@${EC2_HOST} << 'EOF'
        export NVM_DIR="$HOME/.nvm"
        source $NVM_DIR/nvm.sh
        source $NVM_DIR/bash_completion
        nvm use default
        export PATH="$NVM_DIR/versions/node/v22.14.0/bin:$PATH"
        cd /var/www/tcctech-dev/tcctechapinew/
        pm2 restart "TCC-DEV-API"
        EOF
    
    - name: Deploy to staging
      if: github.ref == 'refs/heads/staging'
      env:
        EC2_HOST: ${{ secrets.TCC_STAG_HOST }}
      run: |
        ssh root@${EC2_HOST} << 'EOF'
        export NVM_DIR="$HOME/.nvm"
        source $NVM_DIR/nvm.sh
        source $NVM_DIR/bash_completion
        nvm use default
        export PATH="$NVM_DIR/versions/node/v22.14.0/bin:$PATH"
        cd /var/www/tcctech-stag/tcctechapinew/
        pm2 restart "TCC-Stag-API"
        EOF

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      env:
        EC2_HOST: ${{ secrets.TCC_PROD_HOST }}
      run: |
        ssh ubuntu@${EC2_HOST} << 'EOF'
        export NVM_DIR="$HOME/.nvm"
        source $NVM_DIR/nvm.sh
        source $NVM_DIR/bash_completion
        nvm use default
        export PATH="$NVM_DIR/versions/node/v18.11.0/bin:$PATH"
        cd /home/ubuntu/tcctechapinew/
        pm2 restart "all"
        EOF

